cc_test(
        name = "HeliumLib_test",
        srcs = ["HeliumLib_test.cc"],
        deps = ["//HeliumLib:HeliumLib",
                "@googletest//:gtest_main"],
        size = "small",
)
cc_test(
        name = "SensorCommsLib_test",
        srcs = ["SensorCommsLib_test.cc"],
        deps = ["//SensorCommsLib:SensorCommsLib",
                "@googletest//:gtest_main"],
        size = "small",
)
